---
plugin: aws_ec2
regions:
  - us-east-1
keyed_groups:
  - key: tags.Owner
    prefix: tag
filters:
  instance-state-name : running
  tag:WebServerGroup: Ansible
compose:
  ansible_host: public_ip_address
